/**
 * pytest-writer.ts
 *
 * Renders EnrichedPath[] + WorkflowSpec into a complete pytest file string.
 * Deterministic — no LLM involved at this stage.
 *
 * Output structure:
 *   - Module docstring
 *   - Imports
 *   - make_impls(**overrides) factory — fully data-driven from spec.actionOutputFields
 *   - s() helper
 *   - One async test function per EnrichedPath (with Input/Expected flow/Expected state comments)
 *   - Parametrized boundary test for escalation tiers (only if agent has escalation logic)
 */

import type { EnrichedPath, WorkflowSpec, ActionFieldSpec } from './types';

// Escalation tier boundaries to include as parametrize cases
const TIER_BOUNDARIES = [
  { score: 40,  tier: 'l2_support',     priority: 'normal' },
  { score: 59,  tier: 'l2_support',     priority: 'normal' },
  { score: 60,  tier: 'manager',        priority: 'high' },
  { score: 79,  tier: 'manager',        priority: 'high' },
  { score: 80,  tier: 'senior_manager', priority: 'urgent' },
  { score: 100, tier: 'senior_manager', priority: 'urgent' },
];

export function renderPytestFile(
  paths: EnrichedPath[],
  spec: WorkflowSpec,
  validEmail: string,
): string {
  const lines: string[] = [];

  lines.push(moduleDocstring(spec, paths.length));
  lines.push(imports(spec));
  lines.push('');
  lines.push(pytestMark(spec));
  lines.push('');
  lines.push(makeImplsFactory(spec));
  lines.push('');
  lines.push(helperS());
  lines.push('');
  lines.push('');

  for (const path of paths) {
    lines.push(renderTestFunction(path, spec, validEmail));
    lines.push('');
    lines.push('');
  }

  // Parametrized boundary test (only if agent has escalation_assessment wrapper)
  const hasEscalationWrapper = spec.subagents.some(s =>
    s.name.includes('escalation') && s.beforeSets.length > 0
  );
  if (hasEscalationWrapper) {
    lines.push(renderBoundaryTest(spec));
  }

  return lines.join('\n');
}

// ─── Module docstring ─────────────────────────────────────────────────────────

function moduleDocstring(spec: WorkflowSpec, count: number): string {
  return `"""
E2E tests for ${spec.agentSlug} — auto-generated by \`agentscript gen-tests\`.

Covers ${count} workflow path(s) + escalation tier boundary tests.
Each test uses mock action impls to drive deterministic routing,
while making real LLM calls to DashScope for agent reasoning.

Requires:
    DASHSCOPE_API_KEY environment variable to be set.

Run:
    pytest tests/test_${spec.agentSlug}_e2e.py -v
    pytest tests/test_${spec.agentSlug}_e2e.py -v -k "boundaries"
"""`;
}

// ─── Imports ──────────────────────────────────────────────────────────────────

function imports(spec: WorkflowSpec): string {
  return `import asyncio
import os
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "fixtures"))

from ${spec.fixtureModule} import ${spec.fixtureClass}  # generated fixture`;
}

// ─── pytest.mark.skipif ───────────────────────────────────────────────────────

function pytestMark(spec: WorkflowSpec): string {
  return `pytestmark = pytest.mark.skipif(
    not os.environ.get("DASHSCOPE_API_KEY"),
    reason="DASHSCOPE_API_KEY not set — skipping e2e tests",
)`;
}

// ─── make_impls(**overrides) factory — fully data-driven ─────────────────────

/**
 * Generates a `make_impls(**overrides)` Python function.
 *
 * Design:
 *   - Single parameter: **overrides (dict of field_name → value)
 *   - For each action, generates an async def that returns all declared output
 *     fields, looking up values in `overrides` with a sensible default fallback.
 *   - Callers pass e.g. make_impls(customer_found=False, case_number="CASE-001")
 *     and every action that has a "customer_found" output field will use it.
 */
function makeImplsFactory(spec: WorkflowSpec): string {
  const lines: string[] = [];

  lines.push(`def make_impls(**overrides) -> dict:`);
  lines.push(`    """`);
  lines.push(`    Build a complete mock impls dict for all actions.`);
  lines.push(`    Pass field overrides as keyword arguments, e.g.:`);
  lines.push(`        make_impls(customer_found=False, case_number="CASE-001")`);
  lines.push(`    Any action output field not overridden uses a sensible type-based default.`);
  lines.push(`    """`);
  lines.push(``);

  for (const actionName of spec.actionNames) {
    const fields = spec.actionOutputFields[actionName] ?? [];
    lines.push(...renderActionMock(actionName, fields));
  }

  lines.push(`    return {`);
  for (const actionName of spec.actionNames) {
    lines.push(`        "${actionName}": ${actionName},`);
  }
  lines.push(`    }`);

  return lines.join('\n');
}

/**
 * Renders a single async mock function for one action.
 * Each output field looks up its value in `overrides`, falling back to a
 * type-appropriate default.
 */
function renderActionMock(actionName: string, fields: ActionFieldSpec[]): string[] {
  if (fields.length === 0) {
    return [
      `    async def ${actionName}(**kwargs):`,
      `        return {"ok": overrides.get("ok", True)}`,
      ``,
    ];
  }

  const fieldLines = fields.map(f => {
    const defaultVal = fieldDefault(f);
    return `            "${f.name}": overrides.get("${f.name}", ${defaultVal}),`;
  });

  return [
    `    async def ${actionName}(**kwargs):`,
    `        return {`,
    ...fieldLines,
    `        }`,
    ``,
  ];
}

/**
 * Returns a Python literal for the default value of a field when not overridden.
 * Uses the field type (from ActionFieldSpec) and name patterns for smarter defaults.
 */
function fieldDefault(f: ActionFieldSpec): string {
  const name = f.name;

  // Boolean: fields that represent a success/found/verified flag default to True
  if (f.type === 'boolean') {
    // Failure-indicative names default False (rare); everything else True
    return 'True';
  }

  if (f.type === 'number') return '0';
  if (f.type === 'object') return '{}';

  // String fields: use name-pattern heuristics
  if (name.endsWith('_name') || name === 'name') return '"Test User"';
  if (name.endsWith('_id') || name === 'id') return '"TEST-ID-001"';
  if (name.endsWith('_number') || name.endsWith('_code')) return '"CASE-E2E-001"';
  if (name.endsWith('_status')) return '"active"';
  if (name.endsWith('_tier')) return '"standard"';
  if (name.endsWith('_url')) return '""';
  if (name.endsWith('_date') || name.endsWith('_time')) return '""';
  if (name.endsWith('_address')) return '""';

  return '""';
}

// ─── s() helper ───────────────────────────────────────────────────────────────

function helperS(): string {
  return `def s(bot, name):
    """Shorthand for bot.state.get(name)."""
    return bot.state.get(name)`;
}

// ─── Individual test functions ────────────────────────────────────────────────

function renderTestFunction(path: EnrichedPath, spec: WorkflowSpec, validEmail: string): string {
  const fnName = `test_${path.id}_${toSnake(path.title)}`;
  const isReset = path.title.toLowerCase().includes('reset');
  const isMultiTurn = (path.additionalTurns?.length ?? 0) > 0;

  const lines: string[] = [];
  lines.push(`@pytest.mark.asyncio`);
  lines.push(`async def ${fnName}():`);
  lines.push(`    """`);
  lines.push(`    ${path.title}`);
  lines.push(``);
  lines.push(`    Input:`);
  lines.push(`        ${path.naturalInput}`);
  if (path.additionalTurns?.length) {
    for (const turn of path.additionalTurns) {
      lines.push(`        [Turn 2] ${turn}`);
    }
  }
  lines.push(``);
  lines.push(`    Expected flow:`);
  lines.push(`        ${path.agentChain.join(' → ')}`);
  lines.push(``);
  lines.push(`    Expected state:`);
  for (const [k, v] of Object.entries(path.expectedState)) {
    if (k === '__notes__') continue;
    lines.push(`        ${k} = ${JSON.stringify(v)}`);
  }
  if (path.assertionComments.length) {
    lines.push(``);
    lines.push(`    Notes:`);
    for (const c of path.assertionComments) {
      lines.push(`        ${c}`);
    }
  }
  lines.push(`    """`);

  if (isReset) {
    lines.push(...renderResetTest(path, spec, validEmail));
  } else if (isMultiTurn) {
    lines.push(...renderMultiTurnTest(path, spec, validEmail));
  } else {
    lines.push(...renderSingleTurnTest(path, spec, validEmail));
  }

  return lines.join('\n');
}

/** Renders the make_impls(...) call from path.mocks (open dict of field overrides) */
function renderMocksCall(spec: WorkflowSpec, mocks: Record<string, string | boolean | number | undefined>): string[] {
  const lines: string[] = [`    bot = ${spec.fixtureClass}(impls=make_impls(`];
  for (const [k, v] of Object.entries(mocks)) {
    if (k === '__notes__' || v === undefined) continue;
    lines.push(`        ${k}=${renderPyValue(v)},`);
  }
  lines.push(`    ))`);
  return lines;
}

function renderSingleTurnTest(path: EnrichedPath, spec: WorkflowSpec, validEmail: string): string[] {
  const lines: string[] = [];
  const varNames = new Set(spec.variables.map(v => v.name));

  lines.push(...renderMocksCall(spec, path.mocks));
  lines.push(``);
  lines.push(`    response = await bot.chat(`);
  lines.push(`        "${escapeStr(path.naturalInput)}"`);
  lines.push(`    )`);
  lines.push(``);
  lines.push(`    assert response, "bot must return a non-empty response"`);

  for (const [k, v] of Object.entries(path.expectedState)) {
    if (v === null || k === '__notes__') continue;
    if (!varNames.has(k)) continue;
    const pyVal = renderPyValue(v);
    const comment = getAssertComment(k, v);
    lines.push(`    assert s(bot, "${k}") == ${pyVal}, "${comment}"`);
  }

  return lines;
}

function renderMultiTurnTest(path: EnrichedPath, spec: WorkflowSpec, validEmail: string): string[] {
  const lines: string[] = [];
  const varNames = new Set(spec.variables.map(v => v.name));

  lines.push(...renderMocksCall(spec, path.mocks));
  lines.push(``);
  lines.push(`    # Turn 1`);
  lines.push(`    await bot.chat("${escapeStr(path.naturalInput)}")`);
  lines.push(``);
  lines.push(`    assert s(bot, "customer_verified") is True, "identity verified after turn 1"`);

  // case_number assertion if present in state and mocks
  const caseNumField = spec.variables.find(v => v.name === 'case_number');
  const caseNumMock = path.mocks['case_number'];
  if (caseNumField && caseNumMock) {
    lines.push(`    assert s(bot, "case_number") == "${caseNumMock}", "case created after turn 1"`);
  }
  lines.push(``);

  for (let i = 0; i < (path.additionalTurns?.length ?? 0); i++) {
    lines.push(`    # Turn ${i + 2}`);
    lines.push(`    response = await bot.chat("${escapeStr(path.additionalTurns![i])}")`);
    lines.push(``);
  }

  lines.push(`    assert response, "bot must return a non-empty response"`);

  for (const [k, v] of Object.entries(path.expectedState)) {
    if (v === null || k === '__notes__') continue;
    if (!varNames.has(k)) continue;
    if (k === 'escalation_score') {
      lines.push(`    assert s(bot, "escalation_score") >= 60, f"expected score>=60, got {s(bot, 'escalation_score')}"`);
    } else if (k === 'escalation_tier') {
      lines.push(`    if bot._current_agent_name == "escalation_assessment":`);
      lines.push(`        assert s(bot, "escalation_tier") in ("manager", "senior_manager"), f"got {s(bot, 'escalation_tier')}"`);
      lines.push(`        assert s(bot, "escalation_required") is True`);
    } else if (k === 'escalation_required' && v === true) {
      // escalation_required is only set by after_call when initiate_escalation is called.
      // The LLM may transition to escalation_assessment without calling the action yet,
      // so only assert when the agent is confirmed at escalation_assessment.
      lines.push(`    if bot._current_agent_name == "escalation_assessment":`);
      lines.push(`        # escalation_required may still be False if LLM hasn't called initiate_escalation yet`);
      lines.push(`        pass  # reaching escalation_assessment is sufficient`);
      lines.push(`    # Bot reached escalation flow (at escalation_assessment or response confirms escalation)`);
    } else {
      lines.push(`    assert s(bot, "${k}") == ${renderPyValue(v)}, "${getAssertComment(k, v)}"`);
    }
  }

  return lines;
}

function renderResetTest(path: EnrichedPath, spec: WorkflowSpec, validEmail: string): string[] {
  const varNames = new Set(spec.variables.map(v => v.name));
  const hasEscalationScore = varNames.has('escalation_score');
  const hasCasePriority = varNames.has('case_priority');
  const hasEscalationRequired = varNames.has('escalation_required');

  // Build mocks for the reset test: success with a placeholder case
  const resetMocks = { ...path.mocks };
  delete resetMocks['__notes__'];

  const lines: string[] = [
    `    bot = ${spec.fixtureClass}(impls=make_impls(`,
    ...Object.entries(resetMocks)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `        ${k}=${renderPyValue(v as string | boolean | number)},`),
    `    ))`,
    ``,
    `    # Complete a session first`,
    `    await bot.chat(`,
    `        "Hello, my email is ${validEmail}. I have an issue."`,
    `    )`,
    ``,
    `    # Reset for a new customer`,
    `    bot.reset()`,
    ``,
    `    # All state must be cleared`,
    `    assert s(bot, "customer_verified") is False, "customer_verified must reset"`,
  ];

  if (varNames.has('customer_email')) {
    lines.push(`    assert s(bot, "customer_email") == "", "customer_email must reset"`);
  }
  if (varNames.has('customer_id')) {
    lines.push(`    assert s(bot, "customer_id") == "", "customer_id must reset"`);
  }
  if (varNames.has('case_number')) {
    lines.push(`    assert s(bot, "case_number") == "", "case_number must reset"`);
  }
  if (hasEscalationScore) {
    lines.push(`    assert s(bot, "escalation_score") == 0, f"escalation_score must reset to 0, got {s(bot, 'escalation_score')}"`);
  }
  if (hasCasePriority) {
    lines.push(`    assert s(bot, "case_priority") == "normal", "case_priority must reset to 'normal'"`);
  }
  if (hasEscalationRequired) {
    lines.push(`    assert s(bot, "escalation_required") is False`);
  }

  const startAgent = spec.subagents.find(s => s.isStart)?.name ?? spec.subagents[0]?.name ?? 'start';
  lines.push(`    assert bot._current_agent_name == "${startAgent}"`);
  lines.push(``);
  lines.push(`    # New customer starts fresh`);
  lines.push(`    response = await bot.chat("${escapeStr(path.naturalInput)}")`);
  lines.push(`    assert response, "bot should welcome the next customer"`);

  return lines;
}

// ─── Boundary test ────────────────────────────────────────────────────────────

function renderBoundaryTest(spec: WorkflowSpec): string {
  const escalationSa = spec.subagents.find(s => s.name.includes('escalation'));
  if (!escalationSa) return '';

  const wrapperClass = toPascal(escalationSa.name) + 'Wrapper';

  const params = TIER_BOUNDARIES.map(b =>
    `    pytest.param(${b.score}, "${b.tier}", "${b.priority}", id="score-${b.score}")`
  ).join(',\n');

  return `@pytest.mark.asyncio
@pytest.mark.parametrize("score,expected_tier,expected_priority", [
${params},
])
async def test_escalation_tier_boundaries(score, expected_tier, expected_priority):
    """
    Parametrized boundary test for escalation_assessment before_call tier logic.
    Directly invokes the wrapper to validate thresholds without an LLM call.

    Input:
        Synthetic state with escalation_score set to boundary value.

    Expected flow:
        EscalationAssessmentWrapper.before_call(state) — no LLM

    Expected state:
        escalation_tier and case_priority match the tier table.
    """
    from ${spec.fixtureModule} import ${wrapperClass}, StateManager

    class MockAgent:
        async def __call__(self, msg):
            return type("Msg", (), {"get_text_content": lambda self: "mock"})()

    state = StateManager()
    state.set("escalation_score", score)
    state.set("case_priority", "normal")
    state.set("escalation_tier", "")

    wrapper = ${wrapperClass}(MockAgent(), state, resolve_impl=None)
    await wrapper.before_call(None)

    assert state.get("escalation_tier") == expected_tier, (
        f"score={score}: expected tier '{expected_tier}', got '{state.get('escalation_tier')}'"
    )
    assert state.get("case_priority") == expected_priority, (
        f"score={score}: expected priority '{expected_priority}', got '{state.get('case_priority')}'"
    )`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toSnake(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, 60);
}

function toPascal(s: string): string {
  return s.split('_').map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function renderPyValue(v: string | boolean | number | null): string {
  if (v === null) return 'None';
  if (typeof v === 'boolean') return v ? 'True' : 'False';
  if (typeof v === 'number') return String(v);
  if (v === '') return '""';
  return `"${v}"`;
}

function getAssertComment(key: string, value: unknown): string {
  const repr = typeof value === 'string' ? `'${value}'` : String(value);
  return `${key} should be ${repr}`;
}
