"""
E2E tests for order_tracking_assistant_v1 — auto-generated by `agentscript gen-tests`.

Covers 3 workflow path(s) + escalation tier boundary tests.
Each test uses mock action impls to drive deterministic routing,
while making real LLM calls to DashScope for agent reasoning.

Requires:
    DASHSCOPE_API_KEY environment variable to be set.

Run:
    pytest tests/test_order_tracking_assistant_v1_e2e.py -v
    pytest tests/test_order_tracking_assistant_v1_e2e.py -v -k "boundaries"
"""
import asyncio
import os
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "fixtures"))

from order_tracking_assistant_v1 import AgentBot  # generated fixture

pytestmark = pytest.mark.skipif(
    not os.environ.get("DASHSCOPE_API_KEY"),
    reason="DASHSCOPE_API_KEY not set — skipping e2e tests",
)

def make_impls(**overrides) -> dict:
    """
    Build a complete mock impls dict for all actions.
    Pass field overrides as keyword arguments, e.g.:
        make_impls(customer_found=False, case_number="CASE-001")
    Any action output field not overridden uses a sensible type-based default.
    """

    async def get_customer_info(**kwargs):
        return {
            "customer_found": overrides.get("customer_found", True),
            "customer_name": overrides.get("customer_name", "Test User"),
            "customer_id": overrides.get("customer_id", "TEST-ID-001"),
            "verified": overrides.get("verified", True),
        }

    async def find_order_by_number(**kwargs):
        return {
            "order_found": overrides.get("order_found", True),
            "order_data": overrides.get("order_data", {}),
            "valid_customer": overrides.get("valid_customer", True),
        }

    async def get_order_details(**kwargs):
        return {
            "order_status": overrides.get("order_status", "active"),
            "tracking_number": overrides.get("tracking_number", "CASE-E2E-001"),
            "delivery_date": overrides.get("delivery_date", ""),
            "order_total": overrides.get("order_total", 0),
            "shipping_address": overrides.get("shipping_address", ""),
            "return_eligible": overrides.get("return_eligible", True),
        }

    async def get_tracking_updates(**kwargs):
        return {
            "current_status": overrides.get("current_status", "active"),
            "location": overrides.get("location", ""),
            "updated_delivery_date": overrides.get("updated_delivery_date", ""),
            "delivery_attempts": overrides.get("delivery_attempts", 0),
        }

    async def process_return_request(**kwargs):
        return {
            "return_authorized": overrides.get("return_authorized", True),
            "return_label_url": overrides.get("return_label_url", ""),
            "refund_amount": overrides.get("refund_amount", 0),
            "return_deadline": overrides.get("return_deadline", ""),
        }

    async def report_shipping_issue(**kwargs):
        return {
            "case_number": overrides.get("case_number", "CASE-E2E-001"),
            "resolution_timeframe": overrides.get("resolution_timeframe", ""),
            "escalated": overrides.get("escalated", True),
        }

    return {
        "get_customer_info": get_customer_info,
        "find_order_by_number": find_order_by_number,
        "get_order_details": get_order_details,
        "get_tracking_updates": get_tracking_updates,
        "process_return_request": process_return_request,
        "report_shipping_issue": report_shipping_issue,
    }

def s(bot, name):
    """Shorthand for bot.state.get(name)."""
    return bot.state.get(name)


@pytest.mark.asyncio
async def test_wf01_identity_verification_failure():
    """
    Identity verification failure

    Input:
        Hi, my name is Dan Wu and my email is wudan@wdstudio.com. I need help with my recent order.

    Expected flow:
        order_locator

    Expected state:
        customer_verified = false
        customer_id = ""

    Notes:
        Bot should detect identity verification failure
        Customer verified flag remains false
        No customer ID should be set in state
        Bot should respond with verification failure message
    """
    bot = AgentBot(impls=make_impls(
        customer_found=False,
        customer_name="",
        customer_id="",
    ))

    response = await bot.chat(
        "Hi, my name is Dan Wu and my email is wudan@wdstudio.com. I need help with my recent order."
    )

    assert response, "bot must return a non-empty response"
    assert s(bot, "customer_verified") == False, "customer_verified should be false"
    assert s(bot, "customer_id") == "", "customer_id should be ''"


@pytest.mark.asyncio
async def test_wf02_reset_state_for_a_new_customer_after_completed_session():
    """
    Reset state for a new customer after completed session

    Input:
        Hi, my name is Test User and my email is wudan@wdstudio.com. I'd like to check on order #12345.
        [Turn 2] Thanks for your help! Can I start a new request now?

    Expected flow:
        order_locator

    Expected state:
        customer_verified = false

    Notes:
        After bot.reset(), customer_verified must be false
        Previous case_number and customer_id must be cleared
        New session starts with clean state
        Bot should treat subsequent input as fresh interaction
    """
    bot = AgentBot(impls=make_impls(
        customer_found=True,
        customer_name="Test User",
        customer_id="TEST-ID-001",
        case_number="CASE-E2E-RESET",
    ))

    # Complete a session first
    await bot.chat(
        "Hello, my email is wudan@wdstudio.com. I have an issue."
    )

    # Reset for a new customer
    bot.reset()

    # All state must be cleared
    assert s(bot, "customer_verified") is False, "customer_verified must reset"
    assert s(bot, "customer_email") == "", "customer_email must reset"
    assert s(bot, "customer_id") == "", "customer_id must reset"
    assert s(bot, "case_number") == "", "case_number must reset"
    assert bot._current_agent_name == "order_locator"

    # New customer starts fresh
    response = await bot.chat("Hi, my name is Test User and my email is wudan@wdstudio.com. I'd like to check on order #12345.")
    assert response, "bot should welcome the next customer"


@pytest.mark.asyncio
async def test_wf03_incomplete_input_only_identity_provided_no_issue_type():
    """
    Incomplete input — only identity provided, no issue type

    Input:
        Hi, my name is Test User and my email is wudan@wdstudio.com.

    Expected flow:
        order_locator

    Expected state:
        customer_verified = true

    Notes:
        Bot should confirm identity successfully
        customer_verified must be true after lookup
        Bot should prompt for issue category or problem description
        No case creation or escalation should occur prematurely
    """
    bot = AgentBot(impls=make_impls(
        customer_found=True,
        customer_name="Test User",
        customer_id="TEST-ID-001",
    ))

    response = await bot.chat(
        "Hi, my name is Test User and my email is wudan@wdstudio.com."
    )

    assert response, "bot must return a non-empty response"
    assert s(bot, "customer_verified") == True, "customer_verified should be true"

